spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studentdatabase?createDatabaseIfNotExist=true
      username: root
      password: rojina

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8082
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
student-service-base-url: lb://student-service/student
