spring:
  datasource:
      url: jdbc:mysql://localhost:3306/studentdatabase?createDatabaseIfNotExist=true
      username: root
      password: rojina
      driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernat.dialect.MariaDBDialect
    show-sql: true
server:
  port: 8082
eureka:
  client:
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-server:8761/eureka
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
student-service-base-url: lb://student-service/student
